### ISSUE TITLE
Index out of Range

### ISSUE THREAD

**Issue by sekhar211** [CVMI-Lab/SlotCon#3]
Respected Sir,

While I am executing the code, getting the following error. It will be a very helpful for me if you are getting me out of that error.  

Traceback (most recent call last):
  File "/transfer/detection/convert_pretrain_to_d2.py", line 19, in <module>
    input = sys.argv[1]
IndexError: list index out of range

**Comment by xwen99** [comment]
Hi @sekhar211,
Please make sure you specified the two args correctly when running this command.
