### ISSUE TITLE
/home/sri/SlotCon/detectron2

### ISSUE THREAD

**Issue by Chiya8** [CVMI-Lab/SlotCon#5]
![Screenshot from 2023-02-17 12-13-53](https://user-images.githubusercontent.com/124553603/219569479-5413d3c4-222a-4f6c-b179-8cd84d6f678d.png)
When I run "python train_net.py --config-file /home/sri/SlotCon/transfer/detection/configs/COCO_R_50_FPN_1x_SlotCon.yaml --num-gpus 4 --resume MODEL.WEIGHTS /home/sri/SlotCon/sekhar.pkl OUTPUT_DIR /home/sri/SlotCon/output/COCO_R_50_FPN_1x_sekhar 

it can not find the coco json file.

**Comment by xwen99** [comment]
Hi @Chiya8, 

Please make sure you have correctly arranged the COCO dataset following detectron2's official documents: https://detectron2.readthedocs.io/en/latest/tutorials/builtin_datasets.html
