### ISSUE TITLE
Transfer learning problems

### ISSUE THREAD

**Issue by zhi-xuan-chen** [CVMI-Lab/SlotCon#6]

**Comment by zhi-xuan-chen** [comment]
Thank you for your excellent work!

I want to realize whether the prototypes are useless in the transfer learning process. We just need encoder part in transfer learning?

**Comment by xwen99** [comment]
Hi @zhi-xuan-chen, yes currently we prefer to drop the prototypes, only keep the backbone, and connect it with more advanced task-specific heads for downstream tasks. But in fact, the prototypes could also serve as out-of-the-box semantic segmentation and could be useful if you do not care much about the metrics.

**Comment by zhi-xuan-chen** [comment]
Ok, thank you for your answer! It's very helpful.
