### ISSUE TITLE
Question about 3D model

### ISSUE THREAD

**Issue by zhi-xuan-chen** [CVMI-Lab/SlotCon#7]
Hi, Xin wen!

I am trying to use SlotCon to process 3D data, but some problems hinder me. Such as the operation `torchvision.ops.roi_align` don't provide 3D version. Do you have some solutions for that?

**Comment by xwen99** [comment]
Hi @zhi-xuan-chen, sorry I do not directly work on 3D, but I think modern 3D detection frameworks should consist of similar operators, please check.

**Comment by zhi-xuan-chen** [comment]
Thank you for your reply. I will try to figure it out.
        
    
     
    
        
                    
        
    
 

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            Xin ***@***.***>
            
        
      
      
        
         Date 
        
        
        6/26/2023 17:27
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            Zhi-Xuan ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [CVMI-Lab/SlotCon] Question about 3D model (Issue #7)
        
      
    
  
  
Hi @zhi-xuan-chen, sorry I do not directly work on 3D, but I think modern 3D detection frameworks should consist of similar operators, please check.
