### ISSUE TITLE
KeyError: 'EncoderDecoder is not in the mmengine::model registry. Please check whether the value of `EncoderDecoder`

### ISSUE THREAD

**Issue by sorrowyn** [CVMI-Lab/SlotCon#9]
KeyError: 'EncoderDecoder is not in the mmengine::model registry. Please check whether the value of `EncoderDecoder`

![图片](https://github.com/CVMI-Lab/SlotCon/assets/19569162/494a2bfd-ab1a-4210-8cc3-8e8f9e5e8c2f)

![图片](https://github.com/CVMI-Lab/SlotCon/assets/19569162/5e040941-9557-4260-b164-17d9233a77b8)

Can you provide the versions of these four packages?
```python
mmcv
mmcv-full
mmengine
mmsegmentation
```

**Comment by xwen99** [comment]
Did you compile mmseg from source? If so, please try installing the official release from pypi directly.
Besides, you may check if this issue is helpful: https://github.com/open-mmlab/mmsegmentation/issues/2997

**Comment by sorrowyn** [comment]
![图片](https://github.com/CVMI-Lab/SlotCon/assets/19569162/bc5e7557-3a69-459d-9db5-4db23866d0fe)
Thanks for your reply. I've successfully resolved the issue. Please note that this solution requires ''mmsegmentation<1.0.0''.

Best wishes.

**Comment by xwen99** [comment]
Thx for the information!
